# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    strategy:
        matrix:
            dotnet-version: [ 7.0.x, 8.0.x ] 
            os: [ windows-latest, macos-latest ] 
            chapter: [
                Chapter02/DoToo.sln,
                Chapter03/Chat/BuildChat.sln,
                Chapter03/MauiMigration/MauiMigration.sln,
                Chapter04/News.sln,
                Chapter05/Swiper.sln,
                Chapter06/GalleryApp.sln,
                Chapter07/MeTracker.sln,
                Chapter08/Weather.sln,
                Chapter09-10/SticksAndStones.sln,
                Chapter11/Calculator.sln,
                Chapter12/HotdogOrNot.sln
            ]
                
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Create temporary global.json
      run: >
        echo '{"sdk":{"version": "${{ matrix.dotnet-version }}" }}' > global.json

    - name: Install Maui
      run: dotnet workload install maui --verbosity normal

    - name: Workload restore
      run: dotnet workload restore --verbosity normal  ${{ matrix.chapter }}

    - name: Nuget Restore
      run: dotnet restore --verbosity normal ${{ matrix.chapter }}

    - name: Build
      run: dotnet build --no-restore --verbosity normal ${{ matrix.chapter }}

    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ matrix.chapter }}
